name: Crawler

on:
  push:
    branches:
      - develop

jobs:
  crawl:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Crawler
        run: |
          mkdir data
          echo 'hello' > data/test.txt
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change